name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
      - name: Check
        run: moon check
      - name: Test
        run: moon test
      - name: Build
        run: moon build
